image:
  file: .gitpod.Dockerfile

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - command: |
      cd examples/$EXAMPLE
      pip3 install -r requirements.txt
      [ -e README.md ] && gp open README.md
      clear && dagit
  - openMode: split-right
    command: echo SplitTerminal && clear
