parameters:
  - name: py3_versions
    type: object
    default:
      - "3.6"
      - "3.7"
  - name: py3_env_suffixes
    type: object
    default:
      - api_tests
      - cli_tests
      - core_tests
jobs:
  - job: "dagster"
    pool:
      vmImage: "vs2017-win2016"
    strategy:
      matrix:
        ${{ each py_version in parameters.py3_versions }}:
          ${{ each env_suffix in parameters.py3_env_suffixes }}:
            ${{ replace(py_version, '.', '') }}-windows-${{ env_suffix }}:
              TOXENV: "py${{ replace(py_version, '.', '') }}-windows-${{ env_suffix }}"
              python.version: "${{ py_version }}"
    variables:
      PYTHONLEGACYWINDOWSSTDIO: "1"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"
      - script: choco install vcpython27 --yes
        condition: eq(variables['python.version'], '2.7')
        displayName: "Install vcpython27"
      - script: pip install tox
        displayName: "Install tox"
      - script: cd python_modules\dagster && tox -e %TOXENV% && cd ..\..
        displayName: "Run tests"
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "**/test_results.xml"
          testRunTitle: "dagster $(TOXENV)"
        condition: succeededOrFailed()
