[tool.black]
line-length = 100
skip-string-normalization = true
exclude = '''
/(
    build
  | buck-out
  | dist
  | _build
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | snapshots
)/
'''
target_version = ['py27', 'py36', 'py37', 'py38']
