hacker_news_dbt:
  target: staging
  outputs:
    staging:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: DEMO_DB_STAGING
      warehouse: TINY_WAREHOUSE
      schema: hackernews
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: DEMO_DB
      warehouse: TINY_WAREHOUSE
      schema: hackernews
      client_session_keep_alive: False
