solids:
  produce_training_set:
    config:
      memory_length: 1
  produce_trip_dataset:
    solids:
      load_entire_trip_table:
        config:
          index_label: uuid
        inputs:
          table_name: trips
  produce_weather_dataset:
    solids:
      load_entire_weather_table:
        config:
          index_label: uuid
          subsets:
          - time
        inputs:
          table_name: weather
  upload_training_set_to_gcs:
    inputs:
      bucket_name: dagster-scratch-ccdfe1e
      file_name: training_data