resources:
  pyspark:
    config:
      spark_conf:
        spark:
          jars:
            packages: "com.databricks:spark-csv_2.11:1.5.0"
solids:
  make_weather_samples:
    inputs:
      file_path: dagster_examples/simple_pyspark/sfo_q2_weather_sample.csv
