resources:
  pyspark_step_launcher:
    config:
      cluster_id:
        env: EMR_CLUSTER_ID
      local_pipeline_package_path: "."
      deploy_local_pipeline_package: true
      region_name: "us-west-1"
      staging_bucket: "dagster-scratch-80542c2"
      spark_config:
        spark:
          jars:
            packages: com.databricks:spark-csv_2.11:1.5.0,org.apache.hadoop:hadoop-aws:2.6.5,com.amazonaws:aws-java-sdk:1.7.4
solids:
  make_weather_samples:
    inputs:
      file_path: s3://dagster-airline-demo-source-data/sfo_q2_weather_fixed_header.txt
