version: 2

workflows:
  version: 2
  test:
    jobs:
      - dagster-py36:
          context: coveralls
      - dagster-py35:
          context: coveralls
      - dagster-py27:
          context: coveralls
      - dagit-py36:
          context: coveralls
      - dagit-py35:
          context: coveralls
      - dagit-py27:
          context: coveralls
      - dagit-webapp:
          context: coveralls
      - dagstermill-py36:
          context: coveralls
      - dagstermill-py35:
          context: coveralls
      - dagstermill-py27:
          context: coveralls
      - airline-demo-py36:
          context: coveralls
      - airline-demo-py35:
          context: coveralls
      - airline-demo-py27:
          context: coveralls
      - dagster-contrib-py36:
          context: coveralls
      - dagster-contrib-py35:
          context: coveralls
      - dagster-contrib-py27:
          context: coveralls

      - coverage:
          requires:
            - dagster-py36
            - dagster-py35
            - dagster-py27
            - dagit-py36
            - dagit-py35
            - dagit-py27
            - dagstermill-py36
            - dagstermill-py35
            - dagstermill-py27
            - airline-demo-py36
            - airline-demo-py35
            - airline-demo-py27
            - dagster-contrib-py36
            - dagster-contrib-py35
            - dagster-contrib-py27
          context: coveralls

        

jobs:
  dagster-py36: &dagster-template
    docker:
      - image: circleci/python:3.6.6
    environment:
      TOXENV: py36
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagster Tests
          command: |
            cd python_modules/dagster
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagster/.coverage python_modules/dagster/.coverage.dagster.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagster/
          paths:
            - .coverage*

  dagit-py36: &dagit-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagit Tests
          command: |
            cd python_modules/dagit
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagit/.coverage python_modules/dagit/.coverage.dagit.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagit/
          paths:
            - .coverage*

  dagster-py35:
    <<: *dagster-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagit-py35:
    <<: *dagit-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35


  dagster-py27:
    <<: *dagster-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-py27:
    <<: *dagit-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-webapp:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn

      - run:
          name: Run Typescript
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run ts

      - run:
          name: Run Tests
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run jest

      - run:
          name: Check coding style
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run check-prettier

  dagstermill-py36: &dagstermill-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run dagstermill Tests
          command: |
            cd python_modules/dagstermill
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagstermill/.coverage python_modules/dagstermill/.coverage.dagstermill.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagstermill/
          paths:
            - .coverage*

  dagstermill-py35:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagstermill-py27:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  airline-demo-py36: &airline-demo-template
    <<: *dagster-template
    docker:
      - image: dagster/cci-test:3.6
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py36

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run airline-demo Tests
          command: |
            cd python_modules/airline-demo
            tox -e $TOXENV

      - run:
          command: mv python_modules/airline-demo/.coverage python_modules/airline-demo/.coverage.airline-demo.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/airline-demo/
          paths:
            - .coverage*

  airline-demo-py35:
    <<: *airline-demo-template
    docker:
      - image: dagster/cci-test:3.5
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py35

  airline-demo-py27:
    <<: *airline-demo-template
    docker:
      - image: dagster/cci-test:2.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py27

  coverage:
    docker:
      - image: circleci/python:3.6.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install coverage coveralls

      - attach_workspace:
          at: /tmp/workspace

      - run: |
          cp /tmp/workspace/.coverage* .
          coverage combine
          coveralls


  dagster-contrib-py36: &dagster-contrib-template
    <<: *dagster-template
    docker:
      - image: dagster/cci-test:3.6
    environment:
      TOXENV: py36

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run dagster-contrib Tests
          command: |
            cd python_modules/dagster-contrib
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagster-contrib/.coverage python_modules/dagster-contrib/.coverage.airline-demo.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagster-contrib/
          paths:
            - .coverage*

  dagster-contrib-py35:
    <<: *dagster-contrib-template
    docker:
      - image: dagster/cci-test:3.5
    environment:
      TOXENV: py27

  dagster-contrib-py27:
    <<: *dagster-contrib-template
    docker:
      - image: dagster/cci-test:2.7
    environment:
      TOXENV: py27
