{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dagsterUserDeployments.serviceAccountName" . }}
  labels: {{ include "dagster.labels" . | nindent 4 }}
{{- end -}}
