python_logs:
  dagster_handler_config:
    handlers:
      myHandler:
        class: logging.FileHandler
        level: INFO
        filename: 'my_dagster_logs.log'
        mode: 'a'
        formatter: timeFormatter
    formatters:
      timeFormatter:
        format: '%(asctime)s :: %(message)s'
