apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-celery-worker-env
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DAGSTER_HOME: "{{ template "dagster.celery.dagster_home" .}}"
  DAGSTER_K8S_CELERY_BROKER: {{ template "dagster.celery.broker_url" . }}
  DAGSTER_K8S_CELERY_BACKEND: {{ template "dagster.celery.backend_url" . }}
  {{- if .Values.celery.env -}}
  {{- range $name, $value := .Values.celery.env }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
