apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-instance
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dagster.yaml: |
    scheduler:
      module: dagster_cron.cron_scheduler
      class: SystemCronScheduler

    run_launcher:
      module: dagster_k8s.launcher
      class: K8sRunLauncher
      config:
        {{- with .Values.imagePullSecrets }}
        image_pull_secrets:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        service_account_name: {{ include "dagster.serviceAccountName" . }}
        job_image: "{{ .Values.job_runner.image.repository }}:{{ .Values.job_runner.image.tag }}"
        dagster_home: "{{ template "dagster.dagit.dagster_home" .}}"
        instance_config_map: "{{ template "dagster.fullname" .}}-instance"
        image_pull_policy: "{{ .Values.imagePullPolicy }}"
        job_namespace: "{{ .Release.Namespace }}"
        {{- if .Values.job_runner.env_config_maps }}
        env_config_maps:
          {{- range $name := .Values.job_runner.env_config_maps }}
          {{- if $name }}
            - {{ $name | quote }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.job_runner.env_secrets }}
        env_secrets:
          {{- range $name := .Values.job_runner.env_secrets }}
          {{- if $name }}
            - {{ $name | quote }}
          {{- end }}
          {{- end }}
        {{- end }}


    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername}}
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: {{ template "dagster.postgresql.fullname" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername}}
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: {{ template "dagster.postgresql.fullname" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}
