apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-dagit-env
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DAGSTER_HOME: "{{ template "dagster.dagit.dagster_home" . }}"
{{- if .Values.dagit.env -}}
{{- range $name, $value := .Values.dagit.env }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
