apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-instance
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dagster.yaml: |
    scheduler:
      module: dagster_cron.cron_scheduler
      class: SystemCronScheduler

    schedule_storage:
      module: dagster_postgres.schedule_storage
      class: PostgresScheduleStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername }}
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: {{ include "dagster.postgresql.host" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}

    run_launcher:
      module: dagster_k8s.launcher
      class: K8sRunLauncher
      config:
        {{- with .Values.imagePullSecrets }}
        image_pull_secrets:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        service_account_name: {{ include "dagster.serviceAccountName" . }}
        job_image:
          env: DAGSTER_K8S_PIPELINE_RUN_IMAGE
        dagster_home:
          env: DAGSTER_HOME
        instance_config_map:
          env: DAGSTER_K8S_INSTANCE_CONFIG_MAP
        postgres_password_secret:
          env: DAGSTER_K8S_PG_PASSWORD_SECRET
        image_pull_policy:
          env: DAGSTER_K8S_PIPELINE_RUN_IMAGE_PULL_POLICY
        job_namespace:
          env: DAGSTER_K8S_PIPELINE_RUN_NAMESPACE
        env_config_maps:
        - env:
            DAGSTER_K8S_PIPELINE_RUN_ENV_CONFIGMAP
        {{- if .Values.pipeline_run.env_config_maps }}
        {{- range $name := .Values.pipeline_run.env_config_maps }}
        {{- if $name }}
        - {{ $name | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.pipeline_run.env_secrets }}
        env_secrets:
        {{- range $name := .Values.pipeline_run.env_secrets }}
        {{- if $name }}
        - {{ $name | quote }}
        {{- end }}
        {{- end }}
        {{- end }}

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername }}
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: {{ include "dagster.postgresql.host" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername }}
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: {{ include "dagster.postgresql.host" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}
