resources:
  pyspark_step_launcher:
    config:
      run_config:
        cluster:
          new:
            nodes:
              node_types:
                node_type_id: Standard_DS3_v2
            size:
              num_workers: 1
            spark_version: 6.5.x-scala2.11
        run_name: dagster-tests
      databricks_host: uksouth.azuredatabricks.net
      databricks_token:
        env: DATABRICKS_TOKEN
      local_pipeline_package_path: .
      staging_prefix: /dagster-databricks-tests
      storage:
        s3:
          secret_scope: dagster-databricks-tests
          access_key_key: aws-access-key
          secret_key_key: aws-secret-key
solids:
  make_weather_samples:
    inputs:
      file_path: s3://dagster-databricks-tests/sfo_q2_weather_fixed_header.txt
intermediate_storage:
  s3:
    config:
      s3_bucket: dagster-databricks-tests
      s3_prefix: simple-pyspark
