---
apiVersion: v2
description: Dagster is a system for building modern data applications.
dependencies:
  - name: postgresql
    version: 8.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 12.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.internal
name: dagster
icon: https://raw.githubusercontent.com/dagster-io/dagster/master/assets/Dagster.png
version: 0.1.0
