{{- if .Values.userDeployments.enabled }}
{{ range $deployment := .Values.userDeployments.deployments }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" $ -}}-{{- $deployment.name }}-user-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{ include "dagster.shared_env" $ | nindent 2 }}

  {{- range $name, $value := $deployment.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
---
{{ end }}
{{ end }}
