{{- $userDeployments := index .Values "dagster-user-deployments" }}

{{- if and (not $userDeployments.enabled) $userDeployments.enableSubchart }}
{{ fail "dagster-user-deployments subchart cannot be enabled if workspace.yaml is not created." }}
{{- end }}

{{- if $userDeployments.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-workspace-yaml
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  workspace.yaml:
    load_from:
      {{- $dagitWorkspace := .Values.dagit.workspace }}
      {{- $deployments := ternary $dagitWorkspace.servers $userDeployments.deployments $dagitWorkspace.enabled }}
      {{- range $deployment := $deployments }}
      {{- $deploymentHost := ternary $deployment.host $deployment.name $dagitWorkspace.enabled }}
      - grpc_server:
          host: {{ $deploymentHost }}
          port: {{ $deployment.port }}
          location_name: {{ $deploymentHost }}
      {{- end }}
{{- end }}
