{{- if .Values.dagsterDaemon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" $ -}}-daemon-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{ include "dagster.shared_env" $ | nindent 2 }}
  {{- if .Values.dagsterDaemon.env }}
  {{- range $name, $value := .Values.dagsterDaemon.env }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
---
{{ end }}