{{- if eq .Values.runLauncher.type "CeleryK8sRunLauncher" }}
{{- $celeryK8sRunLauncherConfig := .Values.runLauncher.config.celeryK8sRunLauncher }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-celery
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  celery.yaml: |
    execution:
      celery:
        broker: {{ include "dagster.celery.broker_url" . | quote }}
        backend: {{ include "dagster.celery.backend_url" . | quote }}

        {{- if $celeryK8sRunLauncherConfig.configSource }}
        config_source: {{- $celeryK8sRunLauncherConfig.configSource | toYaml | nindent 10 }}
        {{- end }}
{{- end }}