version: 2

models:
  - name: stories_agg
    description: "HackerNews stories"
    columns: []
  - name: comments_agg
    description: "HackerNews comments"
    columns: []
  - name: user_actions_aggregated
    description: "HackerNews users with enriched data about activity"
    columns: []
